version: 2
jobs:
  run_analyses:
    machine:
      docker_layer_caching: true
    resource_class: large
    working_directory: ~/OpenPBTA-analysis
    steps:
      - checkout

      - run:
          name: Data Download
          command: OPENPBTA_URL=https://open-pbta.s3.amazonaws.com/data OPENPBTA_RELEASE=testing ./scripts/run_in_ci.sh bash download-data.sh

      - run:
          name: List Data Directory Contents
          command: ./scripts/run_in_ci.sh ls data/testing
    
      - run:
          name: Sample Distribution Analyses
          command: ./scripts/run_in_ci.sh bash "analyses/sample-distribution-analysis/run-sample-distribution.sh"

      # The analysis no longer needs to be tested as it has been retired and is better covered by 'SNV Caller Analysis' below.
      #- run:
      #    name: Mutect2 vs Strelka2
      #    command: ./scripts/run_in_ci.sh Rscript -e "rmarkdown::render('analyses/mutect2-vs-strelka2/01-set-up.Rmd', clean = TRUE);
      #                                                rmarkdown::render('analyses/mutect2-vs-strelka2/02-analyze-concordance.Rmd', clean = TRUE)"
     
      - run:
          name: Collapse RSEM
          command: ./scripts/run_in_ci.sh bash analyses/collapse-rnaseq/run-collapse-rnaseq.sh

      - run:
          name: Immune deconvolution using xCell and MCP-Counter
          command: OPENPBTA_DECONV_METHOD="mcp_counter" ./scripts/run_in_ci.sh bash analyses/immune-deconv/run-immune-deconv.sh

      - run:
          name: Fusion standardization and annotation for STARfusion and Arriba with polya and stranded data and creates recurrent fusion list
          command: ./scripts/run_in_ci.sh bash "analyses/fusion_filtering/run_fusion_merged.sh"

      - run:
          name: Transcriptome dimensionality reduction
          command: ./scripts/run_in_ci.sh ./analyses/transcriptomic-dimension-reduction/ci-dimension-reduction-plots.sh 

      - run:
          name: Sex prediction from RNA-seq - Clean data-train elasticnet-evaluate model
          command: OPENPBTA_PERCENT=0 ./scripts/run_in_ci.sh bash analyses/sex-prediction-from-RNASeq/run-sex-prediction-from-RNASeq.sh

      - run:
          name: Selection Strategy Comparison
          command: ./scripts/run_in_ci.sh Rscript -e "rmarkdown::render('analyses/selection-strategy-comparison/01-selection-strategies.rmd', params = list(neighbors = 2), clean = TRUE)"

# This is deprecated       
#      - run:
#          name: ssGSEA Analysis
#          command: OPENPBTA_ANOVAPVALUE=0.25 OPENPBTA_TUKEYPVALUE=0.50 OPENPBTA_PERCKEEP=0.50 ./scripts/run_in_ci.sh bash analyses/ssgsea-hallmark/run-ssgsea-hallmark.sh


# The second method - ControlFREEC - was not included as of v6, so the comparison can no longer be performed
#      - run:
#          name: CNV Caller Comparison  
#          command: ./scripts/run_in_ci.sh Rscript -e "rmarkdown::render('analyses/cnv-comparison/01-cnv-comparison-plotting.Rmd', clean = TRUE)"
  
      - run:
          name: Independent samples
          command: ./scripts/run_in_ci.sh bash analyses/independent-samples/run-independent-samples.sh 

      - run:
          name: Focal CN Preparation
          command: OPENPBTA_XY=0 ./scripts/run_in_ci.sh bash analyses/focal-cn-file-preparation/run-prepare-cn.sh
                
      - run:
          name: Interaction plot
          command: OPENPBTA_ALL=0 ./scripts/run_in_ci.sh bash analyses/interaction-plots/01-create-interaction-plots.sh

      - run:
          name: Mutational Signatures 
          command: ./scripts/run_in_ci.sh Rscript -e "rmarkdown::render('analyses/mutational-signatures/mutational_signatures.Rmd', clean = TRUE)" 
      
      - run:
          name: Tumor mutation burden with TCGA
          command: ./scripts/run_in_ci.sh Rscript -e "rmarkdown::render('analyses/tmb-compare-tcga/compare-tmb.Rmd', clean = TRUE)"

      - run:
          name: Copy number consensus
          command: ./scripts/run_in_ci.sh bash "analyses/copy_number_consensus_call/run_consensus_call.sh"
          
      - run:
          name: Survival analysis
          command: ./scripts/run_in_ci.sh Rscript -e "rmarkdown::render('analyses/survival-analysis/survival-analysis_template.Rmd', params = list(plot_ci = FALSE), clean = TRUE)" 

      - run:
          name: Comparative RNASeq - generate correlation matrix - rsem-tpm.polya
          command: ./scripts/run_in_ci.sh python3 analyses/comparative-RNASeq-analysis/01-correlation-matrix.py ../../data/pbta-gene-expression-rsem-tpm.polya.rds --output-prefix rsem-tpm-polya- --verbose

      - run:
          name: Comparative RNASeq - generate correlation matrix - rsem-tpm.stranded
          command: ./scripts/run_in_ci.sh python3 analyses/comparative-RNASeq-analysis/01-correlation-matrix.py ../../data/pbta-gene-expression-rsem-tpm.stranded.rds --output-prefix rsem-tpm-stranded- --verbose

      - run:
          name: Molecular Subtyping and Plotting - ATRT
          command:  OPENPBTA_SUBSET=0 ./scripts/run_in_ci.sh bash analyses/molecular-subtyping-ATRT/run-molecular-subtyping-ATRT.sh        
      
      - run:
          name: Process SV file
          command: ./scripts/run_in_ci.sh Rscript analyses/sv-analysis/01-process-sv-file.R
          
      - run:
          name: Molecular Subtyping - HGG
          command: OPENPBTA_SUBSET=0 ./scripts/run_in_ci.sh bash analyses/molecular-subtyping-HGG/run-molecular-subtyping-HGG.sh
      
      - run:
          name: Oncoprint plotting
          command: ./scripts/run_in_ci.sh bash "analyses/oncoprint-landscape/run-oncoprint.sh"

      - run:
          name: TP53 NF1 classifier run
          command: OPENPBTA_POLYAPLOT=0 ./scripts/run_in_ci.sh bash "analyses/tp53_nf1_score/run_classifier.sh"  
      
      - run:
          name: GISTIC Plots
          command: ./scripts/run_in_ci.sh Rscript -e "rmarkdown::render('analyses/cnv-chrom-plot/gistic_plot.Rmd', clean = TRUE)"
          
      - run:
          name: SHH TP53 Molecular Subtyping
          command: ./scripts/run_in_ci.sh Rscript -e "rmarkdown::render('analyses/molecular-subtyping-SHH-tp53/SHH-tp53-molecular-subtyping-data-prep.Rmd', clean = TRUE)"

      - run:
          name: Gene set enrichment analysis to generate GSVA scores
          command: OPENPBTA_TESTING=1 ./scripts/run_in_ci.sh bash "analyses/gene-set-enrichment-analysis/run-gsea.sh" 

      - run:
          name: Chromosomal instability breakpoints
          command: ./scripts/run_in_ci.sh bash analyses/chromosomal-instability/run_breakpoint_analysis.sh

      - run:
          name: Fusion Summary
          command: OPENPBTA_TESTING=1 ./scripts/run_in_ci.sh bash "analyses/fusion-summary/run-new-analysis.sh"

      - run:
          name: Molecular subtyping - Non-MB/Non-ATRT Embryonal tumors 
          command: OPENPBTA_SUBSET=0 ./scripts/run_in_ci.sh bash analyses/molecular-subtyping-embryonal/run-embryonal-subtyping.sh

         ################################
         #### Add your analysis here ####
         ################################
     

      - run:
          name: SNV Caller Analysis 
          command: OPENPBTA_VAF_CUTOFF=0.5 ./scripts/run_in_ci.sh bash analyses/snv-callers/run_caller_consensus_analysis.sh
          
       # This analysis was a side concept question and no longer needs to be run. 
       # - run:
          # name: SNV Caller VAF Cutoff Experiment
          # command: ./scripts/run_in_ci.sh Rscript -e "rmarkdown::render('analyses/snv-callers/vaf_cutoff_experiment.Rmd', clean = TRUE)" 
                

  deploy:
    machine: 
      docker_layer_caching: true
    working_directory: ~/OpenPBTA-analysis
    steps:
      - checkout
      - run: ./scripts/run_in_ci.sh echo 'Building image!'
      - run: docker login --username $DOCKER_ID --password $DOCKER_PASSWD
      - run: docker tag open-pbta ccdlopenpbta/open-pbta:latest
      - run: docker push ccdlopenpbta/open-pbta:latest

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - run_analyses

      - deploy:
          requires:
            - run_analyses
          filters:
            # No branch commit will ever trigger this job.
            branches:
              only: master
